services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
      - $HOME/dev/Datasets:/app/Datasets
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
    shm_size: '6gb'
    deploy: {}  # evita erro de chave vazia se for convertido
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
