services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
      - ${HOME}/dev/Datasets:/app/Datasets
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
    shm_size: '6gb'
    privileged: true  # <-- aqui!
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
