pretrained_models:
  rgb: MobileNetV3LargePlusPlus
  depth: MobileNetV3LargePlusPlus

upsample:
  - [76, 38, 3, 1, 1]
  - [118, 60, 3, 1, 1]
  - [188, 94, 3, 1, 1]
  - [296, 148, 3, 1, 1]
  - [432, 216, 3, 1, 1, scale: 1]
  - [640, 320, 3, 1, 1]
  - [960, 480, 3, 1, 1, scale: 1]

conv:
  - [38, 1, 1]
  - [60, 1, 1]
  - [94, 1, 1]

afd_semantic:
  - [960, 0.0625]
  - [160, 0.0625]
  - [112, 0.0625]
  - [80, 0.0625]

afd_spatial:
  - 80
  - 40
  - 24
  - 16
