pretrained_models:
  rgb: MobileNetV3Large
  depth: MobileNetV3Large

upsample:
  - [108, 54, 3, 1, 1]
  - [184, 92, 3, 1, 1]
  - [320, 160, 3, 1, 1]
  - [560, 280, 3, 1, 1]
  - [960, 480, 3, 1, 1]

conv:
  - [54, 1, 1]
  - [92, 1, 1]
  - [160, 1, 1]

afd_semantic:
  - [960, 0.0625]
  - [80, 0.0625]
  - [40, 0.0625]

afd_spatial:
  - 40
  - 24
  - 16
